# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/INTRA/esmost/workspace/project/vivado/project_Audio/project_Audio.cache/wt [current_project]
set_property parent.project_path /home/INTRA/esmost/workspace/project/vivado/project_Audio/project_Audio.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  /home/INTRA/esmost/workspace/project/MIX_001/ip_repo/Audio_Mixer
  /home/INTRA/esmost/workspace/project/audioip_lab4
  /home/INTRA/esmost/workspace/project/repo/FILTER_IIR_1.0
  /home/INTRA/esmost/workspace/project/repo/Volume_Pregain_1.0
  /home/INTRA/esmost/workspace/project/vivado/ip_repo/myip_1.0
  /home/INTRA/esmost/workspace/project/audioip_lab4/zedboard_audio
} [current_project]
add_files /home/INTRA/esmost/workspace/project/vivado/project_Audio/project_Audio.srcs/sources_1/bd/Audio/Audio.bd
set_property used_in_implementation false [get_files -all /home/INTRA/esmost/workspace/project/vivado/project_Audio/project_Audio.srcs/sources_1/bd/Audio/ip/Audio_processing_system7_0_0/Audio_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/esmost/workspace/project/vivado/project_Audio/project_Audio.srcs/sources_1/bd/Audio/ip/Audio_rst_processing_system7_0_100M_0/Audio_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/esmost/workspace/project/vivado/project_Audio/project_Audio.srcs/sources_1/bd/Audio/ip/Audio_rst_processing_system7_0_100M_0/Audio_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/esmost/workspace/project/vivado/project_Audio/project_Audio.srcs/sources_1/bd/Audio/ip/Audio_rst_processing_system7_0_100M_0/Audio_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/esmost/workspace/project/vivado/project_Audio/project_Audio.srcs/sources_1/bd/Audio/ip/Audio_xbar_0/Audio_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/esmost/workspace/project/vivado/project_Audio/project_Audio.srcs/sources_1/bd/Audio/ip/Audio_auto_pc_0/Audio_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/INTRA/esmost/workspace/project/vivado/project_Audio/project_Audio.srcs/sources_1/bd/Audio/Audio_ooc.xdc]
set_property is_locked true [get_files /home/INTRA/esmost/workspace/project/vivado/project_Audio/project_Audio.srcs/sources_1/bd/Audio/Audio.bd]

read_vhdl -library xil_defaultlib /home/INTRA/esmost/workspace/project/vivado/project_Audio/project_Audio.srcs/sources_1/bd/Audio/hdl/Audio_wrapper.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/INTRA/esmost/workspace/project/audioip_lab4/zedboard_audio/constraints/zed_audio.xdc
set_property used_in_implementation false [get_files /home/INTRA/esmost/workspace/project/audioip_lab4/zedboard_audio/constraints/zed_audio.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Audio_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef Audio_wrapper.dcp

catch { report_utilization -file Audio_wrapper_utilization_synth.rpt -pb Audio_wrapper_utilization_synth.pb }
